#include <Pack/RPAudio.h>

// asset generated by dtk
#include <Pack/RPAudio/rp_Static_sound.brsar.inc>

/**
 * @brief Constructor
 */
RPSndStaticMgr::RPSndStaticMgr() : EGG::ArcPlayer(NULL) {
    for (int i = 0; i < WPAD_MAX_CONTROLLERS; i++) {
        mInfo[i].unk0 = 0;
    }
}

/**
 * @brief Destructor
 */
RPSndStaticMgr::~RPSndStaticMgr() {}

/**
 * @brief Mounts the static sound archive
 *
 * @return Success
 */
bool RPSndStaticMgr::setupArchive() {
    mSoundHeap = &RP_GET_INSTANCE(RPSndAudioMgr)->getSoundHeap();

    bool success = setupMemoryArchive(
                       sStaticSoundArchive,
                       &RP_GET_INSTANCE(RPSndAudioMgr)->getSoundHeap()) != NULL;

    return success;
}

// /**
//  * @brief Updates the state of the sound player
//  */
// void RPSndStaticMgr::calc() {
//     if (!mIsInitialized) {
//         return;
//     }

//     EGG::ArcPlayer::calc();
// }
